# Generated by Django 5.0.6 on 2024-06-08 18:04

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField()),
                ('street', models.CharField()),
                ('homeNumber', models.CharField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BottlesInAutomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plasticBottlesNow', models.IntegerField(default=0)),
                ('plasticBottlesLimit', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserBottleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositedBottles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('bottlesInAutomatId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bottlesinautomat')),
            ],
        ),
        migrations.CreateModel(
            name='BottlesCollectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('plasticBottlesCollected', models.IntegerField(default=0)),
                ('machineId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTime', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('eventType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eventtype')),
                ('machineId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.machine')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userBalanceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userbalance'),
        ),
        migrations.AddField(
            model_name='user',
            name='userBottleDetailsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userbottledetails'),
        ),
    ]
