# Generated by Django 5.0.6 on 2024-06-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineevent',
            name='eventType',
            field=models.CharField(choices=[('DEPOSIT_BOTTLE', 'Deposit Bottle'), ('STOP', 'Stop')], max_length=20),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
